name: Compliance

on: pull_request

jobs:
  compliance_job:
    runs-on: ubuntu-latest
    name: Run compliance checks on patch series (PR)
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        path: wfa_qt_app
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-doc-pip

    - name: Install python dependencies
      working-directory: wfa_qt_app
      run: |
        pip3 install -U pip
        pip3 install -U setuptools
        pip3 install -U wheel
        grep -E "python-magic|junitparser|lxml|gitlint|pylint|pykwalify|yamllint" scripts/requirements-fixed.txt | xargs pip3 install -U

    - name: Clone Zephyr downstream
      env:
        BASE_REF: ${{ github.base_ref }}
      working-directory: wfa_qt_app
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote -v
        # Ensure there's no merge commits in the PR
        [[ "$(git rev-list --merges --count origin/${BASE_REF}..)" == "0" ]] || \
        (echo "::error ::Merge commits not allowed, rebase instead";false)

        git rebase origin/${BASE_REF}
        # debug
        git log  --pretty=oneline | head -n 10
        # Clone downstream Zephyr (no west needed as we only need the scripts)
        git clone https://github.com/nrfconnect/sdk-zephyr

    - name: Run CODEOWNERS test
      id: codeowners
      env:
        BASE_REF: ${{ github.base_ref }}
      working-directory: wfa_qt_app
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        ./scripts/ci/codeowners.py -c origin/${BASE_REF}..

    - name: Run Compliance Tests
      continue-on-error: true
      id: compliance
      env:
        BASE_REF: ${{ github.base_ref }}
      working-directory: wfa_qt_app
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        export ZEPHYR_BASE="$(dirname "$(pwd)")/wfa_qt_app/sdk-zephyr"
        # debug
        ls -la
        git log --pretty=oneline | head -n 10
        # For now we run KconfigBasic, but we should transition to Kconfig
        $ZEPHYR_BASE/scripts/ci/check_compliance.py --annotate \
        -e KconfigBasic \
        -e checkpatch  \
        -e Kconfig \
        -e DevicetreeBindings \
        -c origin/${BASE_REF}..

    - name: upload-results
      uses: actions/upload-artifact@v3
      continue-on-error: true
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      with:
        name: compliance.xml
        path: wfa_qt_app/compliance.xml

    - name: check-warns
      working-directory: wfa_qt_app
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        export ZEPHYR_BASE="$(dirname "$(pwd)")/wfa_qt_app/sdk-zephyr"
        if [[ ! -s "compliance.xml" ]]; then
          exit 1;
        fi

        files=($($ZEPHYR_BASE/scripts/ci/check_compliance.py -l))
        for file in "${files[@]}"; do
          f="${file}.txt"
          if [[ -s $f ]]; then
            errors=$(cat $f)
            errors="${errors//'%'/'%25'}"
            errors="${errors//$'\n'/'%0A'}"
            errors="${errors//$'\r'/'%0D'}"
            echo "::error file=${f}::$errors"
            exit=1
          fi
        done

        if [ "${exit}" == "1" ]; then
          exit 1;
        fi
