name: Compliance Checks

on: pull_request

jobs:
  check_compliance:
    runs-on: ubuntu-22.04
    name: Run compliance checks on patch series (PR)
    steps:
    - name: Update PATH for west
      run: |
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 0

    - name: cache-pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-doc-pip

    - name: Install python dependencies
      run: |
        pip3 install setuptools
        pip3 install wheel
        pip3 install python-magic lxml junitparser gitlint pylint pykwalify yamllint
        pip3 install west

    - name: Clone Zephyr downstream
      env:
        BASE_REF: ${{ github.base_ref }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "Your Name"
        git remote -v
        # Ensure there's no merge commits in the PR
        #[[ "$(git rev-list --merges --count origin/${BASE_REF}..)" == "0" ]] || \
        #(echo "::error ::Merge commits not allowed, rebase instead";false)
        git rebase origin/${BASE_REF}
        # debug
        git log  --pretty=oneline | head -n 10
        # Clone downstream Zephyr (no west needed as we only need the scripts)
        git clone https://github.com/nrfconnect/sdk-zephyr

    - name: Run CODEOWNERS test
      id: codeowners
      env:
        BASE_REF: ${{ github.base_ref }}
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        ./scripts/ci/codeowners.py -c origin/${BASE_REF}..

    - name: Run Compliance Tests
      continue-on-error: true
      id: compliance
      env:
        BASE_REF: ${{ github.base_ref }}
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        export ZEPHYR_BASE="$(dirname "$(pwd)")/sdk-hostap/sdk-zephyr"
        # debug
        ls -la
        git log  --pretty=oneline | head -n 10
        $ZEPHYR_BASE/scripts/ci/check_compliance.py --annotate -e ModulesMaintainers -e KconfigBasicNoModules -e KconfigBasic -e Kconfig \
        -c origin/${BASE_REF}..

    - name: upload-results
      uses: actions/upload-artifact@v3
      continue-on-error: true
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      with:
        name: compliance.xml
        path: sdk-hostap

    - name: check-warns
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        echo $(pwd)
        ls -la
        export ZEPHYR_BASE="$(dirname "$(pwd)")/sdk-hostap/sdk-zephyr"
        if [[ ! -s $(dirname "$(pwd)")/sdk-hostap/compliance.xml ]]; then
          echo "::error ::compliance.xml not found in $(dirname "$(pwd)")/sdk-hostap/compliance.xml"
          exit 1;
        fi

        files=($($ZEPHYR_BASE/scripts/ci/check_compliance.py -l))
        for file in "${files[@]}"; do
          f="${file}.txt"
          if [[ -s $f ]]; then
            errors=$(cat $f)
            errors="${errors//'%'/'%25'}"
            errors="${errors//$'\n'/'%0A'}"
            errors="${errors//$'\r'/'%0D'}"
            echo "::error file=${f}::$errors"
            exit=1
          fi
        done

        if [ "${exit}" == "1" ]; then
          exit 1;
        fi

    - name: Get sdk-hostap main branch commit
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      run: |
        git fetch origin main
        echo "MAIN_SHA=$(git rev-parse origin/main)" >> $GITHUB_ENV

    - name: Check nRF sauce tags
      if: contains(github.event.pull_request.user.login, 'dependabot[bot]') != true
      uses: nrfconnect/action-commit-tags@v1
      with:
        target: $GITHUB_WORKSPACE
        revrange: $MAIN_SHA..${{ github.event.pull_request.head.sha }}
